### PR TITLE
ZipMeta: Memory Footprint Fix

### PR DESCRIPTION
**Pull request by ms-xy**
Fixed the memory footprint of the zipmeta service by using mmap instead of reading the whole file.
(Before when reading a zip64 (>4GB e.g.) it would also consume the size of the archive in system memory)
Also cleaned up the code a bit.

### CODE REVIEW

**Comment by ms-xy** [comment]
Please note: What still needs a fix (or rather implementation) is support for truncated files, this is not included in this fix. Current behaviour is to only analyze the central directory (which isn't there necessarily).

**Comment by webstergd** [comment]
can you create an issue for the fix? Once you are done I will merge the request

**Comment by ms-xy** [comment]
Updated the branch

**Comment by webstergd** [comment]
I dont see a docker and docker-compose addition. However, we are still playing with that so I am going to go ahead a merge and we can fix that later.

**Pull request merged**
